{% set version = "4.0.7" %}

package:
  name: filelock
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/f/filelock/filelock-{{ version }}.tar.gz
  sha256: da5915714a70b55d167fdc7e251ad91302b0a36816fb574dfafae8f4f2c9bb21

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs >=0.5
    - hatchling >=1.29
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - filelock
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/tox-dev/py-filelock
  summary: A platform independent file lock.
  doc_url: https://py-filelock.readthedocs.io
  dev_url: https://github.com/tox-dev/py-filelock
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jakirkham
    - mariusvniekerk
    - nicoddemus
