{% set name = "filelock" %}
{% set version = "3.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 261e8674273052f1bb97e4e381fdef93163610e56607f6953a5087b418a88886

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps .

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=1.11.1
    - hatch-vcs >=0.3

  run:
    - python >=3.7

test:
  imports:
    - filelock

about:
  home: https://github.com/tox-dev/py-filelock
  license: Unlicense
  license_file: LICENSE
  summary: A platform independent file lock.

extra:
  recipe-maintainers:
    - jakirkham
    - mariusvniekerk
    - nicoddemus
