{% set name = "filelock" %}
{% set version = "3.0.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
   fn: {{ name }}-{{ version }}.tar.gz
   url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
   sha256: 59ccab92fe118da7e5ce5a9fcd95506ade58d9d5f606db4922192524edfac820

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - filelock

about:
  home: https://github.com/benediktschmitt/py-filelock
  license: Public Domain
  summary: 'A platform independent file lock.'

extra:
  recipe-maintainers:
    - jakirkham
    - mariusvniekerk
