{% set version = "4.0.3" %}

package:
  name: filelock
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/f/filelock/filelock-{{ version }}.tar.gz
  sha256: 87296d60478e14204fd9406e79831400fef76693bae2895deec236c98e87a8aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs >=0.5
    - hatchling >=1.29
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - filelock
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/tox-dev/py-filelock
  summary: A platform independent file lock.
  doc_url: https://py-filelock.readthedocs.io
  dev_url: https://github.com/tox-dev/py-filelock
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jakirkham
    - mariusvniekerk
    - nicoddemus
