{% set name = "filelock" %}
{% set version = "3.20.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8360948b351b80f420878d8516519a2204b07aefcdcfd24912a5d33127f188c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps .

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.11.1
    - hatch-vcs >=0.3

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - filelock

about:
  home: https://github.com/tox-dev/py-filelock
  license: Unlicense
  license_file: LICENSE
  summary: A platform independent file lock.

extra:
  recipe-maintainers:
    - jakirkham
    - mariusvniekerk
    - nicoddemus
